[package]
authors = ["sabinonweb <sabinonweb7@gmail.com>"]
name = "mesh-core-no-std"
edition = "2021"
version = "0.1.0"

[dependencies]
# Core embedded crates
critical-section = { version = "1.2.0", default-features = false, features = ["restore-state-u32"] }
heapless = "0.9.1"
static_cell = "2.1.1"
futures = { version = "0.3.31", default-features = false }

# Panic & logging
defmt = "0.3"
defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }
panic-halt = "1.0.0"

# Embassy async runtime
esp-hal = { version = "0.19.0", features = [
    "esp32s3",
    "embassy-futures", "embassy-sync", "async",
    "embedded-io", "embedded-io-async"
] }
embassy-executor    = { version = "0.5.0", features = ["nightly"] }
embassy-sync = "0.6.0"
embassy-time = { version = "0.5.0", features = ["tick-hz-1_000"] }

# ESP HAL for S3 (new crate)
embedded-hal = "1.0.0"
esp-println = "0.16.1"


[dependencies.portable-atomic]
version = "1.11.1"
features = ["critical-section"]

[package.metadata.cargo-xbuild]
memory = "memory.x"

[profile.dev]
opt-level = 's'
codegen-units = 1

[profile.release]
opt-level = 's'

# trade compile speed for slightly better optimisations
codegen-units = 1
# Use Link Time Optimisations to further inline things across
# crates
lto = 'fat'
# Leave the debug symbols in (default is no debug info)
debug = 2

